sudo: required
dist: trusty # 指定 ubuntu 版本
branches:
  only:
    - master
# 只需要自定义下面五个量
env:
 global:
   - GITHUB_NAME: Gal@Builder            # 瞎填都可以
   - GITHUB_MAIL: galseraph@gmail.com    # 瞎填都可以
   - GITHUB_USER: GalAster               # 你的用户名
   - GITHUB_REPO: Geis                   # 你的项目名
   # 还有一个 TRAVIS_KEY 填在 travis settings 里!
   # 教程 https://0x0.life/archives/47a3aed6.html
before_script:
  - export TZ='Asia/Shanghai'
  - git config --global user.name "${GITHUB_NAME}"
  - git config --global user.email "${GITHUB_MAIL}"
script:
  # 使用要求 10 次提交之类有 tag 存在, 名称必须为 v1.0.0 类似的形式
  - git clone --depth 10 --branch master --single-branch https://github.com/${GITHUB_USER}/${GITHUB_REPO}
  - cd ${GITHUB_REPO}
  - ver=`git tag | awk 'END {print}'`
  - nVer=`echo $ver | awk -F. '{printf "%s.%s.%s\n",$1,$2,$3+1}'`
  - echo $ver
  - cd ..
before_deploy:
  - git tag -a "$nVer" -m "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - cd ${GITHUB_REPO}
  # 清理工程文件
  - rm -rf .git
  - rm -rf Packages/_*
  - rm -rf Resources
  - rm -f .travis.yml
  - rm -f .gitignore
  # 清理文档(可选)
  - rm -rf Documentation
  - ls && cd ..
  - tar -cJf ${GITHUB_REPO}.tar.xz ${GITHUB_REPO}
deploy:
  provider: releases
  api_key: ${TRAVIS_KEY}
  name: AutoBuild-$nVer
  prerelease: true
  file:
    - ${GITHUB_REPO}.tar.xz
  skip_cleanup: true
  on:
    repo: ${GITHUB_USER}/${GITHUB_REPO}